spring:
  application:
    name: client-b
  boot:
    admin:
      url: https://spring-admin-server.cfapps.io
      client:
         enabled: true
         health-url: https://client-b.cfapps.io/health
         management-url: https://client-b.cfapps.io
         service-url: https://client-b.cfapps.io