spring:
  application:
    name: client-a
  boot:
    admin:
      url: https://spring-admin-server.cfapps.io
      client:
         enabled: true
         health-url: http://${vcap.application.uris[0]}/health
         management-url: http://${vcap.application.uris[0]}
         service-url: http://${vcap.application.uris[0]}